(* 目的: 月と日から星座名を返却する *)
(* seiza : int -> int -> string *)
let seiza x y =
  if x = 1 then       if      y >  0 && y < 20 then "やぎ座"
                      else if y > 19 && y < 32 then "みずがめ座"
                      else ""
  else if x = 2  then if      y >  0 && y < 19 then "みずがめ座"
                      else if y > 18 && y < 30 then "うお座"
                      else ""
  else if x = 3  then if      y >  0 && y < 21 then "うお座"
                      else if y > 20 && y < 32 then "おひつじ座"
                      else ""
  else if x = 4  then if      y >  0 && y < 20 then "おひつじ座"
                      else if y > 19 && y < 31 then "おうし座"
                      else ""
  else if x = 5  then if      y >  0 && y < 21 then "おうし座"
                      else if y > 20 && y < 32 then "ふたご座"
                      else ""
  else if x = 6  then if      y >  0 && y < 22 then "ふたご座"
                      else if y > 21 && y < 31 then "かに座"
                      else ""
  else if x = 7  then if      y >  0 && y < 23 then "かに座"
                      else if y > 22 && y < 32 then "しし座"
                      else ""
  else if x = 8  then if      y >  0 && y < 23 then "しし座"
                      else if y > 22 && y < 32 then "おとめ座"
                      else ""
  else if x = 9  then if      y >  0 && y < 23 then "おとめ座"
                      else if y > 22 && y < 31 then "てんびん座"
                      else ""
  else if x = 10 then if      y >  0 && y < 24 then "てんびん座"
                      else if y > 23 && y < 32 then "さそり座"
                      else ""
  else if x = 11 then if      y >  0 && y < 23 then "さそり座"
                      else if y > 22 && y < 31 then "いて座"
                      else ""
  else if x = 12 then if      y >  0 && y < 22 then "いて座"
                      else if y > 21 && y < 32 then "やぎ座"
                      else ""
  else ""

(* テスト *)
(* c.f. http://www.study-style.com/seiza/12seiza.html *)
let test_oh1 = seiza 3 21 = "おひつじ座"
let test_oh2 = seiza 4 19 = "おひつじ座"
let test_ou1 = seiza 4 20 = "おうし座"
let test_ou2 = seiza 5 20 = "おうし座"
let test_fu1 = seiza 5 21 = "ふたご座"
let test_fu2 = seiza 6 21 = "ふたご座"
let test_ka1 = seiza 6 22 = "かに座"
let test_ka2 = seiza 7 22 = "かに座"
let test_si1 = seiza 7 23 = "しし座"
let test_si2 = seiza 8 22 = "しし座"
let test_ot1 = seiza 8 23 = "おとめ座"
let test_ot2 = seiza 9 22 = "おとめ座"
let test_te1 = seiza 9 23 = "てんびん座"
let test_te2 = seiza 10 23 = "てんびん座"
let test_sa1 = seiza 10 24 = "さそり座"
let test_sa2 = seiza 11 22 = "さそり座"
let test_it1 = seiza 11 23 = "いて座"
let test_it2 = seiza 12 21 = "いて座"
let test_ya1 = seiza 12 22 = "やぎ座"
let test_ya2 = seiza 1 19 = "やぎ座"
let test_mi1 = seiza 1 20 = "みずがめ座"
let test_mi2 = seiza 2 18 = "みずがめ座"
let test_uo1 = seiza 2 19 = "うお座"
let test_uo2 = seiza 3 20 = "うお座"
